export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMON_BY_ID_REQUEST = 'GET_POKEMON_BY_ID_REQUEST';
export const GET_POKEMON_BY_ID_SUCCESS = 'GET_POKEMON_BY_ID_SUCCESS';
export const GET_POKEMON_BY_ID_FAILURE = 'GET_POKEMON_BY_ID_FAILURE';
